version: "3"

services:
  bot:
    image: "mefchik/phys-journal-tg-bot:latest"
    restart: always
    container_name: tg-phys-bot
    env_file: ".env"
    volumes:
      - db:/app/bot
      - log_volume:/app/bot/_logs

volumes:
  db:
  log_volume:
