version: "3"

services:
  bot:
    image: "mefchik/phys-journal-tg-bot:latest"
    restart: always
    container_name: tg-phys-bot
    env_file: ".env"
    volumes:
      - db:/app

volumes:
  db:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 0.0.0.0/0
